FROM python:3.12.13-slim
WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY convert.py ./
RUN python convert.py
COPY download.py ./
RUN python download.py 

COPY . .

CMD [ "python", "./main.py" ]
